wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691457035.507333
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 19
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 3
      - 5
epochs:
  desc: null
  value: 2
model_architecture:
  desc: null
  value: UNet
